### ISSUE TITLE
How do you authenticate with last.fm

### ISSUE THREAD

**Issue by spudart** [uoziod/chrome-soundcloud-scrobbler#6]
I installed the extension, but I don't see how to authenticate with last.fm.

**Comment by uoziod** [comment]
Do you see this?

![image](https://cloud.githubusercontent.com/assets/169145/15558014/30322776-22d7-11e6-8c86-6cff9363d32c.png)

**Comment by spudart** [comment]
@uoziod Oh, I see! That works. Thank you.
